### ISSUE TITLE
Bug : Not able to attach energy

### ISSUE THREAD

**Issue by z-mehta** [h0111in/PokemonGoBack#42]
@h0111in 
not able to attach energy to "Geodude"........the attached energy is not shown on the GUI..

**Comment by h0111in** [comment]
I checked it but I could not find that. maybe it is already fixed.check the latest code.
*please attach log file which explains a bug

**Comment by z-mehta** [comment]
just upload the latest code on github

**Comment by z-mehta** [comment]
it is still not showing energy attach to Pokemon - Geodude

**Comment by z-mehta** [comment]
@h0111in it is still not showing energy attach to Pokemon - Geodude

**Comment by z-mehta** [comment]
@h0111in  after attaching energy to Geodude, it is showing the following error:

Jun 22, 2017 10:31:56 PM Model.Player popCard
INFO: A37
java.lang.IndexOutOfBoundsException: Index: 9, Size: 5
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at Model.Player.addCard(Player.java:104)
	at Controller.LogicController$2.MoveCard(LogicController.java:539)
	at View.GameBoardController.fireMoveCard(GameBoardController.java:347)
	at View.GameBoardController$5.handle(GameBoardController.java:319)
	at View.GameBoardController$5.handle(GameBoardController.java:286)

**Comment by h0111in** [comment]
this issue is fixed in latest update.
if the issue is no longer observed, please close  the issue it helps me to manage easier.

**Comment by z-mehta** [comment]
the issue has been fixed.....thanks @h0111in
